### ISSUE TITLE
Context menu tool creates reg file in wrong directory

### ISSUE THREAD

**Issue by edutiron** [Tyronnosaurus/ComicResizer#2]
The 'Add to context menu' button creates an auxiliar reg file that is automatically run to edit the registry. It is created in the application's directory.
However, when the application is run from a file's context menu, using this tool creates the reg file in the file's directory instead.

**Comment by Tyronnosaurus** [comment]
Repaired

**Comment by edutiron** [comment]
Repaired.
Same problem was happening with the Config.ini file that stores user settings. Also repaired.
